# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='Código')),
                ('acronym', models.CharField(max_length=200, unique=True, verbose_name='Acronimo')),
            ],
            options={
                'verbose_name_plural': 'unidades de medida',
                'verbose_name': 'unidad de medida',
            },
        ),
    ]
