# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='Código')),
                ('acronym', models.CharField(max_length=200, unique=True, verbose_name='Acronimo')),
                ('stocks', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('supplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy.Supplies')),
            ],
            options={
                'verbose_name': 'equipamiento médico',
                'verbose_name_plural': 'equipamientos médicos',
            },
            bases=('pharmacy.supplies',),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('supplies_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy.Supplies')),
            ],
            options={
                'verbose_name': 'equipamiento médico',
                'verbose_name_plural': 'equipamientos médicos',
            },
            bases=('pharmacy.supplies',),
        ),
    ]
