# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_supplies_measuring_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplies',
            old_name='stocks',
            new_name='stock',
        ),
    ]
