# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20170322_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'medicina', 'verbose_name_plural': 'medicinas'},
        ),
    ]
