# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(max_length=200, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'raza',
            },
        ),
        migrations.CreateModel(
            name='AnimalColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Tipo Animal',
                'verbose_name_plural': 'Tipo de Animales',
            },
        ),
        migrations.CreateModel(
            name='MedicalConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('first_image', models.ImageField(upload_to='uploads/')),
                ('second_image', models.ImageField(upload_to='uploads/')),
                ('third_image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'consulta medica',
                'verbose_name_plural': 'consultas medicas',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('height', models.FloatField(verbose_name='Peso')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('animal_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalConsultation.AnimalBreed', verbose_name='Raza')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicalConsultation.AnimalType', verbose_name='Tipo de Animal')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('primary_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_color', to='medicalConsultation.AnimalColor', verbose_name='Color Primario')),
                ('second_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_color', to='medicalConsultation.AnimalColor', verbose_name='Color Secundario')),
            ],
            options={
                'verbose_name': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('tagline', models.CharField(blank=True, max_length=140)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'veterinario',
                'verbose_name_plural': 'veterinarios',
            },
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalConsultation.Patient', verbose_name='paciente'),
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='veterinarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalConsultation.Veterinarian', verbose_name='veterinario'),
        ),
        migrations.AddField(
            model_name='animalbreed',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalConsultation.AnimalType', verbose_name='Tipo de Animal'),
        ),
        migrations.AlterUniqueTogether(
            name='animalbreed',
            unique_together=set([('code', 'animal_type')]),
        ),
    ]
