# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'raza',
            },
        ),
        migrations.CreateModel(
            name='DogColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('height', models.FloatField(verbose_name='Peso')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('dog_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalConsultation.DogBreed', verbose_name='Raza')),
                ('primary_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_color', to='medicalConsultation.DogColor', verbose_name='Color Primario')),
                ('second_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_color', to='medicalConsultation.DogColor', verbose_name='Color Secundario')),
            ],
            options={
                'verbose_name': 'paciente',
            },
        ),
    ]
