# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0002_auto_20170322_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_image',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
