# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0002_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='action',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
