# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0003_auditor_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditor',
            name='action',
            field=models.CharField(max_length=40),
        ),
    ]
