# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0003_patient_first_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
