# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0004_auto_20170324_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconsultation',
            name='first_image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='second_image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalconsultation',
            name='third_image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
