# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicalConsultation', '0004_auto_20170505_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
